ember: &defaults
  image: pvycode/emberapp
  volumes:
    - .:/app
    - /app/node_modules/

npm:
  <<: *defaults
  command: npm

bower:
  <<: *defaults
  command: bower --allow-root

client:
  <<: *defaults
  ports:
    - "4200:4200"
    - "7020:7020"
    - "7357:7357"